name: Node - SSH deploy

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    SFTP-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest

        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2

            - name: Use Node.js 16
              uses: actions/setup-node@v2-beta
              with:
                  node-version: '16'

            - name: 🔨 Build Project
              run: |
                  npm install --force
                  npm run build

            - name: 📂 Deploy to Server
              uses: easingthemes/ssh-deploy@v2.1.5
              env:
                  REACT_APP_AUTH0_DOMAIN: ${{ secrets.REACT_APP_AUTH0_DOMAIN }}
                  REACT_APP_AUTH0_CLIENT_ID: ${{ secrets.REACT_APP_AUTH0_CLIENT_ID }}
                  REACT_APP_API_SERVER_URL: ${{ secrets.REACT_APP_API_SERVER_UR }}
                  REACT_APP_AUTH0_AUDIENCE: https://dev-urpwjajvkrsjwg6l.us.auth0.com/api/v2/
                  REACT_APP_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}
                  REACT_APP_VERSION:  v1.1.0
                  GENERATE_SOURCEMAP: false
                  # ARGS: "-rltgoDzvO --delete"
                  SOURCE: 'build/'
                  REMOTE_HOST: 192.34.62.123
                  REMOTE_USER: mantis
                  TARGET: public_html
                  EXCLUDE: '/dist/, /node_modules/'
